'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  Nextra6x7b:
    resources:
      instance-type: A100-80G
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: |-
        apt-get update && apt-get install -y --no-install-recommends \
          ca-certificates \
          build-essential \
          git \
          python \
          python-pip \
          python-setuptools
        git clone https://github.com/PanQiWei/AutoGPTQ
        cd AutoGPTQ
        git checkout v0.5.1
        pip3 install .
        cd ..
        pip3 install --upgrade transformers optimum
        pip install accelerator
        python run hello.py \
          --result-dir=/outputs/model
      image: nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04
