'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  Nextra6x7b:
    resources:
      instance-type: C5
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: |-
        apt-get update && apt-get install -y --no-install-recommends ca-certificates build-essential git python python-pip python-setuptools
        pip3 install accelerator, auto-gptq
        python run workflow/download.py \
          --result-dir=/outputs/model
      image: ubuntu:latest
